<script lang="ts" setup>
import FutureContractIntervalSelector from '@/components/futures/FutureContractIntervalSelector.vue'
import {
  createFutureStrategySegmentApi,
  deleteFutureStrategySegmentsApi,
  getFutureContractIntervalList,
  getFutureContractList,
  getFutureStrategySegmentListApi,
  updateFutureStrategySegmentApi,
  type FutureContract,
  type FutureContractInterval,
  type FutureStrategySegmentCreateParams,
  type FutureStrategySegmentItem,
  type FutureStrategySegmentRole,
} from '@/api/modules'
import { formatDateTime as formatDateTimeByDayjs } from '@/utils/date'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { computed, onMounted, reactive, ref } from 'vue'

interface SegmentForm {
  original_segment_role?: FutureStrategySegmentRole
  original_segment_index?: number
  segment_role: FutureStrategySegmentRole
  segment_index?: number
  direction: 'up' | 'down'
  start_time: string
  start_price?: number
  end_time: string
  end_price?: number
  kline_count?: number
  confirmed_at: string
}

const TEXT = {
  title: '期货策略分析管理',
  subtitle: '当前先支持线段管理；买卖点管理后续再补充。',
  filterTitle: '合约与周期',
  filterSubtitle: '选择期货合约和周期后，可查看并维护当前策略线段。',
  refresh: '刷新线段',
  create: '新增线段',
  batchDelete: '批量删除',
  emptySelection: '请先选择合约和周期',
  emptySegments: '当前周期暂无线段',
  loadOptionsError: '获取合约或周期列表失败',
  loadSegmentsError: '获取线段列表失败',
  createSuccess: '新增线段成功',
  createError: '新增线段失败',
  updateSuccess: '修改线段成功',
  updateError: '修改线段失败',
  deleteSuccessPrefix: '批量删除成功，已删除 ',
  deleteSuccessSuffix: ' 条线段',
  deleteError: '批量删除线段失败',
  deleteTitle: '确认删除',
  deleteMessagePrefix: '确定删除已选中的 ',
  deleteMessageSuffix: ' 条线段吗？',
  tableTitle: '线段列表',
  tableSubtitlePrefix: '当前查看：',
  role: '类型',
  direction: '方向',
  segmentIndex: '编号',
  startTime: '起点时间',
  startPrice: '起点价格',
  endTime: '终点时间',
  endPrice: '终点价格',
  klineCount: 'K线数',
  confirmedAt: '确认时间',
  action: '操作',
  edit: '修改',
  addDialogTitle: '新增线段',
  editDialogTitle: '修改线段',
  confirm: '确认',
  cancel: '取消',
  roleConfirmed: '已确认',
  roleCurrent: '当前线段',
  rolePending: '候选线段',
  directionUp: '上涨',
  directionDown: '下跌',
  contractPlaceholder: '请选择合约',
  autoGenerated: '系统自动生成',
  autoCalculated: '系统自动计算',
  notAvailable: '-',
} as const

const ROLE_OPTIONS = [
  { label: TEXT.roleConfirmed, value: 'confirmed' },
  { label: TEXT.roleCurrent, value: 'current' },
  { label: TEXT.rolePending, value: 'pending' },
] as const satisfies Array<{ label: string; value: FutureStrategySegmentRole }>

const DIRECTION_OPTIONS = [
  { label: TEXT.directionUp, value: 'up' },
  { label: TEXT.directionDown, value: 'down' },
] as const

const DATETIME_VALUE_FORMAT = 'YYYY-MM-DDTHH:mm:ss'

const contracts = ref<FutureContract[]>([])
const intervals = ref<FutureContractInterval[]>([])
const segments = ref<FutureStrategySegmentItem[]>([])
const selectedRows = ref<FutureStrategySegmentItem[]>([])
const selectedSymbol = ref('')
const selectedInterval = ref<number>()
const optionsLoading = ref(false)
const tableLoading = ref(false)
const submitting = ref(false)
const batchDeleting = ref(false)
const dialogVisible = ref(false)
const dialogMode = ref<'create' | 'edit'>('create')
const formRef = ref<FormInstance>()
const tableRef = ref()

const form = reactive<SegmentForm>({
  segment_role: 'confirmed',
  direction: 'up',
  start_time: '',
  start_price: undefined,
  end_time: '',
  end_price: undefined,
  kline_count: undefined,
  confirmed_at: '',
})

const rules = reactive<FormRules<SegmentForm>>({
  segment_role: [{ required: true, message: '请选择线段类型', trigger: 'change' }],
  direction: [{ required: true, message: '请选择线段方向', trigger: 'change' }],
  start_time: [{ required: true, message: '请选择起点时间', trigger: 'change' }],
  start_price: [{ required: true, message: '请输入起点价格', trigger: 'blur' }],
  end_time: [{ required: true, message: '请选择终点时间', trigger: 'change' }],
  end_price: [{ required: true, message: '请输入终点价格', trigger: 'blur' }],
})

const hasSelection = computed(() => Boolean(selectedSymbol.value && selectedInterval.value))
const isEditMode = computed(() => dialogMode.value === 'edit')
const dialogTitle = computed(() => (isEditMode.value ? TEXT.editDialogTitle : TEXT.addDialogTitle))
const emptyText = computed(() => (hasSelection.value ? TEXT.emptySegments : TEXT.emptySelection))
const canBatchDelete = computed(() => selectedRows.value.length > 0 && hasSelection.value)
const contractOptions = computed(() => {
  return contracts.value.map((contract) => ({
    label: `${contract.symbol} · ${contract.name}`,
    value: contract.symbol,
    description: contract.name,
  }))
})
const intervalOptions = computed(() => {
  return intervals.value.map((interval) => ({
    label: interval.contract_interval_name || formatInterval(interval.seconds),
    value: interval.seconds,
  }))
})
const currentSelectionText = computed(() => {
  if (!hasSelection.value) {
    return TEXT.emptySelection
  }

  const contract = contracts.value.find((item) => item.symbol === selectedSymbol.value)
  const interval = intervals.value.find((item) => item.seconds === selectedInterval.value)
  return `${TEXT.tableSubtitlePrefix}${contract?.symbol || selectedSymbol.value} · ${interval?.contract_interval_name || formatInterval(selectedInterval.value || 0)}`
})

const formatInterval = (seconds: number) => {
  if (seconds % (60 * 60 * 24) === 0) {
    return `${seconds / (60 * 60 * 24)}D`
  }
  if (seconds % (60 * 60) === 0) {
    return `${seconds / (60 * 60)}H`
  }
  if (seconds % 60 === 0) {
    return `${seconds / 60}F`
  }
  return `${seconds}S`
}

const formatDateTime = (value?: Parameters<typeof formatDateTimeByDayjs>[0]) => {
  return formatDateTimeByDayjs(value)
}

const formatNumber = (value?: number | string | null) => {
  if (value === null || value === undefined || value === '') {
    return TEXT.notAvailable
  }

  const numericValue = Number(value)
  if (Number.isNaN(numericValue)) {
    return TEXT.notAvailable
  }

  return numericValue.toLocaleString('zh-CN', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 4,
  })
}

const extractErrorMessage = (error: unknown, fallback: string) => {
  if (typeof error === 'object' && error !== null) {
    const response = error as { data?: { detail?: string; msg?: string } }
    if (response.data?.detail) {
      return response.data.detail
    }
    if (response.data?.msg) {
      return response.data.msg
    }
  }

  return fallback
}

const getRoleLabel = (role: FutureStrategySegmentRole) => {
  return {
    confirmed: TEXT.roleConfirmed,
    current: TEXT.roleCurrent,
    pending: TEXT.rolePending,
  }[role]
}

const getRoleTagType = (role: FutureStrategySegmentRole) => {
  return {
    confirmed: 'success',
    current: 'primary',
    pending: 'warning',
  }[role] as 'success' | 'primary' | 'warning'
}

const getDirectionLabel = (direction: string) => {
  return direction === 'up' ? TEXT.directionUp : TEXT.directionDown
}

const resetSelection = () => {
  selectedRows.value = []
  tableRef.value?.clearSelection?.()
}

const resetForm = () => {
  form.original_segment_role = undefined
  form.original_segment_index = undefined
  form.segment_role = 'confirmed'
  form.segment_index = undefined
  form.direction = 'up'
  form.start_time = ''
  form.start_price = undefined
  form.end_time = ''
  form.end_price = undefined
  form.kline_count = undefined
  form.confirmed_at = ''
  formRef.value?.clearValidate()
}

const applySegmentList = (items: FutureStrategySegmentItem[]) => {
  segments.value = items
  resetSelection()
}

const loadSegments = async () => {
  if (!hasSelection.value || !selectedInterval.value) {
    segments.value = []
    resetSelection()
    return
  }

  tableLoading.value = true
  try {
    const result = await getFutureStrategySegmentListApi({
      symbol: selectedSymbol.value,
      interval: selectedInterval.value,
    })
    applySegmentList(result.items)
  } catch (error) {
    segments.value = []
    resetSelection()
    ElMessage.error(extractErrorMessage(error, TEXT.loadSegmentsError))
  } finally {
    tableLoading.value = false
  }
}

const loadOptions = async () => {
  optionsLoading.value = true
  try {
    const [contractList, intervalList] = await Promise.all([
      getFutureContractList(),
      getFutureContractIntervalList(),
    ])

    contracts.value = contractList
    intervals.value = intervalList

    if (!contractList.length || !intervalList.length) {
      selectedSymbol.value = ''
      selectedInterval.value = undefined
      segments.value = []
      resetSelection()
      return
    }

    if (!contractList.some((item) => item.symbol === selectedSymbol.value)) {
      selectedSymbol.value = contractList[0]?.symbol || ''
    }
    if (!intervalList.some((item) => item.seconds === selectedInterval.value)) {
      selectedInterval.value = intervalList[0]?.seconds
    }

    await loadSegments()
  } catch (error) {
    ElMessage.error(extractErrorMessage(error, TEXT.loadOptionsError))
  } finally {
    optionsLoading.value = false
  }
}

const handleContractChange = async (value: string) => {
  selectedSymbol.value = value
  await loadSegments()
}

const handleIntervalChange = async (value: number | string) => {
  selectedInterval.value = Number(value)
  await loadSegments()
}

const handleSelectionChange = (rows: FutureStrategySegmentItem[]) => {
  selectedRows.value = rows
}

const openCreateDialog = () => {
  if (!hasSelection.value) {
    ElMessage.warning(TEXT.emptySelection)
    return
  }

  dialogMode.value = 'create'
  resetForm()
  dialogVisible.value = true
}

const openEditDialog = (row: FutureStrategySegmentItem) => {
  dialogMode.value = 'edit'
  form.original_segment_role = row.segment_role
  form.original_segment_index = row.segment_index
  form.segment_role = row.segment_role
  form.segment_index = row.segment_index
  form.direction = row.direction as 'up' | 'down'
  form.start_time = row.start_time
  form.start_price = Number(row.start_price)
  form.end_time = row.end_time
  form.end_price = Number(row.end_price)
  form.kline_count = row.kline_count
  form.confirmed_at = row.confirmed_at || ''
  formRef.value?.clearValidate()
  dialogVisible.value = true
}

const buildSegmentPayload = (): FutureStrategySegmentCreateParams => {
  return {
    symbol: selectedSymbol.value,
    interval: Number(selectedInterval.value),
    segment_role: form.segment_role,
    direction: form.direction,
    start_time: form.start_time,
    start_price: Number(form.start_price),
    end_time: form.end_time,
    end_price: Number(form.end_price),
  }
}

const submitForm = async () => {
  if (!formRef.value || !hasSelection.value) {
    return
  }

  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) {
    return
  }

  submitting.value = true
  try {
    const payload = buildSegmentPayload()

    if (isEditMode.value) {
      const result = await updateFutureStrategySegmentApi({
        ...payload,
        original_segment_role: form.original_segment_role || form.segment_role,
        original_segment_index: form.original_segment_index || 1,
      })
      applySegmentList(result.items)
      ElMessage.success(TEXT.updateSuccess)
    } else {
      const result = await createFutureStrategySegmentApi(payload)
      applySegmentList(result.items)
      ElMessage.success(TEXT.createSuccess)
    }

    dialogVisible.value = false
  } catch (error) {
    ElMessage.error(extractErrorMessage(error, isEditMode.value ? TEXT.updateError : TEXT.createError))
  } finally {
    submitting.value = false
  }
}

const handleBatchDelete = async () => {
  if (!canBatchDelete.value || !selectedInterval.value) {
    return
  }

  try {
    await ElMessageBox.confirm(
      `${TEXT.deleteMessagePrefix}${selectedRows.value.length}${TEXT.deleteMessageSuffix}`,
      TEXT.deleteTitle,
      {
        type: 'warning',
      },
    )
  } catch {
    return
  }

  batchDeleting.value = true
  try {
    const result = await deleteFutureStrategySegmentsApi({
      symbol: selectedSymbol.value,
      interval: selectedInterval.value,
      items: selectedRows.value.map((item) => ({
        segment_role: item.segment_role,
        segment_index: item.segment_index,
      })),
    })
    await loadSegments()
    ElMessage.success(`${TEXT.deleteSuccessPrefix}${result.deleted}${TEXT.deleteSuccessSuffix}`)
  } catch (error) {
    ElMessage.error(extractErrorMessage(error, TEXT.deleteError))
  } finally {
    batchDeleting.value = false
  }
}

onMounted(() => {
  void loadOptions()
})
</script>

<template>
  <div class="pageBox strategy-analysis-manager">
    <header class="page-header">
      <div>
        <h2 class="title">{{ TEXT.title }}</h2>
        <p class="subtitle">{{ TEXT.subtitle }}</p>
      </div>
      <div class="page-actions">
        <el-button :loading="optionsLoading || tableLoading" @click="loadSegments">{{ TEXT.refresh }}</el-button>
        <el-button type="primary" :disabled="!hasSelection" @click="openCreateDialog">
          {{ TEXT.create }}
        </el-button>
        <el-button
          type="danger"
          :loading="batchDeleting"
          :disabled="!canBatchDelete"
          @click="handleBatchDelete"
        >
          {{ TEXT.batchDelete }}
        </el-button>
      </div>
    </header>

    <section class="panel">
      <div class="panel-header">
        <div>
          <h3 class="panel-title">{{ TEXT.filterTitle }}</h3>
          <p class="panel-subtitle">{{ TEXT.filterSubtitle }}</p>
        </div>
      </div>
      <FutureContractIntervalSelector
        :selected-contract="selectedSymbol"
        :selected-period="selectedInterval"
        :contract-options="contractOptions"
        :period-options="intervalOptions"
        :contract-loading="optionsLoading"
        :contract-disabled="optionsLoading || !contracts.length"
        :period-disabled="optionsLoading || !intervals.length"
        :contract-placeholder="TEXT.contractPlaceholder"
        @update:selected-contract="handleContractChange"
        @update:selected-period="handleIntervalChange"
      />
    </section>

    <section class="panel">
      <div class="panel-header">
        <div>
          <h3 class="panel-title">{{ TEXT.tableTitle }}</h3>
          <p class="panel-subtitle">{{ currentSelectionText }}</p>
        </div>
      </div>

      <el-table
        ref="tableRef"
        v-loading="tableLoading"
        :data="segments"
        border
        row-key="segment_index"
        :empty-text="emptyText"
        @selection-change="handleSelectionChange"
      >
        <el-table-column type="selection" width="52" />
        <el-table-column prop="segment_index" :label="TEXT.segmentIndex" width="88" />
        <el-table-column :label="TEXT.role" width="120">
          <template #default="{ row }">
            <el-tag :type="getRoleTagType(row.segment_role)">{{ getRoleLabel(row.segment_role) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="TEXT.direction" width="90">
          <template #default="{ row }">
            {{ getDirectionLabel(row.direction) }}
          </template>
        </el-table-column>
        <el-table-column prop="start_time" :label="TEXT.startTime" min-width="180">
          <template #default="{ row }">
            {{ formatDateTime(row.start_time) }}
          </template>
        </el-table-column>
        <el-table-column prop="start_price" :label="TEXT.startPrice" min-width="120">
          <template #default="{ row }">
            {{ formatNumber(row.start_price) }}
          </template>
        </el-table-column>
        <el-table-column prop="end_time" :label="TEXT.endTime" min-width="180">
          <template #default="{ row }">
            {{ formatDateTime(row.end_time) }}
          </template>
        </el-table-column>
        <el-table-column prop="end_price" :label="TEXT.endPrice" min-width="120">
          <template #default="{ row }">
            {{ formatNumber(row.end_price) }}
          </template>
        </el-table-column>
        <el-table-column prop="kline_count" :label="TEXT.klineCount" width="100" />
        <el-table-column :label="TEXT.action" width="120" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" link @click="openEditDialog(row)">{{ TEXT.edit }}</el-button>
          </template>
        </el-table-column>
      </el-table>
    </section>

    <el-dialog v-model="dialogVisible" :title="dialogTitle" width="40rem" @closed="resetForm">
      <el-form ref="formRef" :model="form" :rules="rules" label-width="8rem">
        <div class="form-grid">
          <el-form-item :label="TEXT.role" prop="segment_role">
            <el-select v-model="form.segment_role" placeholder="请选择线段类型">
              <el-option
                v-for="option in ROLE_OPTIONS"
                :key="option.value"
                :label="option.label"
                :value="option.value"
              />
            </el-select>
          </el-form-item>

          <el-form-item v-if="isEditMode" :label="TEXT.segmentIndex">
            <el-input :model-value="String(form.segment_index ?? '')" disabled />
          </el-form-item>

          <el-form-item :label="TEXT.direction" prop="direction">
            <el-select v-model="form.direction" placeholder="请选择线段方向">
              <el-option
                v-for="option in DIRECTION_OPTIONS"
                :key="option.value"
                :label="option.label"
                :value="option.value"
              />
            </el-select>
          </el-form-item>

          <el-form-item v-if="isEditMode" :label="TEXT.klineCount">
            <el-input :model-value="String(form.kline_count ?? TEXT.autoCalculated)" disabled />
          </el-form-item>

          <el-form-item :label="TEXT.startTime" prop="start_time">
            <el-date-picker
              v-model="form.start_time"
              type="datetime"
              style="width: 100%"
              :value-format="DATETIME_VALUE_FORMAT"
            />
          </el-form-item>

          <el-form-item :label="TEXT.startPrice" prop="start_price">
            <el-input-number
              v-model="form.start_price"
              :precision="4"
              :step="0.01"
              controls-position="right"
              style="width: 100%"
            />
          </el-form-item>

          <el-form-item :label="TEXT.endTime" prop="end_time">
            <el-date-picker
              v-model="form.end_time"
              type="datetime"
              style="width: 100%"
              :value-format="DATETIME_VALUE_FORMAT"
            />
          </el-form-item>

          <el-form-item :label="TEXT.endPrice" prop="end_price">
            <el-input-number
              v-model="form.end_price"
              :precision="4"
              :step="0.01"
              controls-position="right"
              style="width: 100%"
            />
          </el-form-item>

          <el-form-item v-if="isEditMode" :label="TEXT.confirmedAt">
            <el-input
              :model-value="form.confirmed_at ? formatDateTime(form.confirmed_at) : TEXT.notAvailable"
              disabled
            />
          </el-form-item>
        </div>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">{{ TEXT.cancel }}</el-button>
        <el-button type="primary" :loading="submitting" @click="submitForm">{{ TEXT.confirm }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style lang="less" scoped>
.strategy-analysis-manager {
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.page-header,
.page-actions,
.panel-header {
  display: flex;
}

.page-header,
.panel-header {
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}

.page-actions {
  gap: 12px;
}

.title,
.panel-title {
  margin: 0;
  color: #303133;
}

.title {
  font-size: 20px;
  font-weight: 600;
}

.subtitle,
.panel-subtitle {
  margin-top: 6px;
  color: #909399;
  font-size: 13px;
}

.panel {
  padding: 16px;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  background-color: #fff;
}

.panel-header {
  margin-bottom: 16px;
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0 16px;
}

@media (max-width: 960px) {
  .page-header {
    flex-direction: column;
    align-items: flex-start;
  }

  .form-grid {
    grid-template-columns: 1fr;
  }
}
</style>
